/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jt_scoutserver_utils_SystemUtils */

#ifndef _Included_com_jt_scoutserver_utils_SystemUtils
#define _Included_com_jt_scoutserver_utils_SystemUtils
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_jt_scoutserver_utils_SystemUtils
	* Method:    hasNewDevices
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_jt_scoutserver_utils_SystemUtils_hasNewDevices
	(JNIEnv *, jclass);

	/*
	* Class:     com_jt_scoutserver_utils_SystemUtils
	* Method:    nativeInit
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_com_jt_scoutserver_utils_SystemUtils_nativeInit
	(JNIEnv *, jclass);

	/*
	* Class:     com_jt_scoutserver_utils_SystemUtils
	* Method:    nativeExit
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_jt_scoutserver_utils_SystemUtils_nativeExit
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
